# Generated by Django 5.0.1 on 2024-02-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_product_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_sales",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_sales_amount",
            field=models.FloatField(default=0),
        ),
    ]
