# Generated by Django 5.0.1 on 2024-02-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_remove_cart_items_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="product",
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="products",
            field=models.ManyToManyField(to="myapp.product"),
        ),
    ]
