# Generated by Django 5.0.1 on 2024-02-02 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_orderdetail_product_orderdetail_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="product_rating",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="total_rating_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
