# Generated by Django 5.0.1 on 2024-02-02 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_productreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reviewed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="reviewed_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ProductReview",
        ),
    ]
